# Use a minimal, secure Java 17 Runtime Environment (JRE)
FROM eclipse-temurin:17-jre-alpine

# DevSecOps Best Practice: Create a non-root system user
RUN addgroup -S appuser && adduser -S appuser -G appuser

# Set the working directory inside the container
WORKDIR /app

# Copy the compiled JAR file from the 'target/' directory.
COPY target/*.jar app.jar

# Enforce security by switching from the 'root' user to our restricted user
USER appuser:appuser

# Document the default Spring Boot port
EXPOSE 8080

# Command to run the application
# Use 'exec' form for better signal handling (SIGTERM)
ENTRYPOINT ["java", "-jar", "app.jar"]